version: '3.8'

services:
  frontend:
    build:
      context: ./SPC-Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./SPC-Back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  ia:
    build:
      context: ./SPC-IA
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge